# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleramReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('telname', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
